# Informazioni sul sito
title: Il Mio Sito Jekyll
email: tuo@email.com
description: >- # questo significa ignorare newline fino a "baseurl:"
  Scrivi qui una breve descrizione del tuo sito. Apparirà nei risultati di ricerca
  e nel feed RSS.
baseurl: "" # il sottopath del tuo sito, e.g. /blog
url: "https://www.tuosito.com" # l'host base & protocollo per il tuo sito, e.g. http://example.com

# Social media
twitter_username: tuousername
github_username:  tuousername
telegram_username: tuousername
facebook_username: tuousername
instagram_username: tuousername
linkedin_username: tuousername

# Impostazioni di build
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Esclusioni dalla conversione
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CHANGELOG.md
  - LICENSE
  - .gitignore

# Impostazioni Sass
sass:
  sass_dir: _sass
  style: compressed

# Impostazioni delle collezioni
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Impostazioni di default per i post
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Il tuo nome"
      comments: true

# Impostazioni di paginazione
paginate: 5
paginate_path: "/blog/page:num/"

# Impostazioni SEO
twitter:
  username: tuousername
  card: summary_large_image
logo: /assets/images/logo.png
social:
  name: Il tuo nome
  links:
    - https://twitter.com/tuousername
    - https://www.facebook.com/tuousername
    - https://www.linkedin.com/in/tuousername
    - https://github.com/tuousername
    - https://t.me/tuousername

# Analytics
google_analytics: UA-XXXXXXXX-X
google_site_verification: your-google-site-verification-code

# Commenti (esempio con Disqus)
disqus:
  shortname: your-disqus-shortname

# Altre impostazioni personalizzate
author: Il tuo nome
timezone: Europe/Rome
lang: it

# Impostazioni per le immagini
img_path: /assets/images/

# Opzioni per il feed RSS
feed:
  path: feed.xml

# Impostazioni per la ricerca (se utilizzi un plugin di ricerca)
search: true

# Impostazioni per la compressione HTML (se utilizzi un plugin di compressione)
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]

# Impostazioni per il caching
# Uncomment the following line if you want to enable caching
# jekyll-cache: true

# Impostazioni per i link permanenti
permalink: /:categories/:title/

# Impostazioni per i tag
tag_page_layout: tag_page
tag_page_dir: tag
